### PR TITLE
Fix raffler

### PR DESCRIPTION
**Pull request by dennisdegreef**
This PR is now targeting the `fix-listing` branch and continues #27

### CODE REVIEW

**Comment by rdohms** [comment]
@dennisdegreef looking good. are you done? asking because of [wip]

**Comment by dennisdegreef** [comment]
I think I'm done yes :) extra testing would be nice though.

**Comment by rdohms** [comment]
@dennisdegreef we can work on that in separate, also the auto-deploy branch has full on integration testing

**Comment by dennisdegreef** [comment]
I removed the WIP.

With extra testing, I ment manual testing at least :) I agree we can work on automated testing later in. My manual testing involved trying to raffle with `[0,1,2,3]` selected avatars.

**Comment by dennisdegreef** [comment]
🙌

**Pull request merged**
